  name: Deploy to Github Pages
  on:
    push:
      branches:
        - main
  jobs:
    gh-pages-deploy:
      name: Deploying to Github Pages
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
              node-version: 'latest'
          - uses: pnpm/action-setup@v2
            with:
              version: 8
          - name: Install packages
            run: pnpm i
          - name: Set Creds
            run: git config user.name "efficks" && git config user.email "fx@efficks.com"
          - name: Deploy
            run: pnpm run deploy